# Site settings
title: "Gurpreet Singh"
bye_message: "Thx!"
baseurl: "/"
url: "https://guppster.github.io"
disqus: Gurpreet Singh

# Header settings
nick: "Gurpreet Singh"
mail:
    domain: "protonmail"
    ext: "ch"
source_code: 
    server: "github.com"
    nick: "guppster"
blog: 
    server: "wordpress.com"
    nick: "guppster"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
